# Generated by Django 3.1.7 on 2021-04-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tags',
            table='Tags',
        ),
    ]
