# Generated by Django 3.1.7 on 2021-04-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210413_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelTable(
            name='tags',
            table=None,
        ),
    ]
