# Generated by Django 3.1.7 on 2021-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210413_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
