# Generated by Django 3.1.7 on 2021-04-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210416_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='file',
            new_name='media_file',
        ),
    ]
