# Generated by Django 3.1.7 on 2021-04-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210416_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='media_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
