# Generated by Django 3.1.7 on 2021-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210422_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blogs.Tags'),
        ),
    ]
