# Generated by Django 3.1.7 on 2021-04-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20210423_0736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
    ]
