# Generated by Django 3.1.7 on 2021-04-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_delete_leaderboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Comments'},
        ),
    ]
