# Generated by Django 3.1.7 on 2021-04-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20210424_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activity'},
        ),
    ]
